//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contacts_windowsform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_table
    {
        public int contact_id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Edit_check { get; set; }
    }
}
